email:
  enabled: true
  from: suhasmkumar66@gmail.com
  host: smtp.gmail.com
  password: mzal hfmd cvle vbft
  port: 587
  subject: New Ireland IT Jobs
  to:
  - suhasroxxy@gmail.com
  user: suhasmkumar66@gmail.com
greenhouse_companies:
- slug: microsoft
  website: ''
- slug: dell-ireland
  website: ''
- slug: apple-ireland
  website: ''
- slug: oracle
  website: ''
- slug: facebook
  website: ''
- slug: sandisk
  website: ''
- slug: kingston
  website: ''
- slug: vmware
  website: ''
- slug: intel-ireland
  website: ''
- slug: maxim-integrated-products
  website: ''
- slug: eircom
  website: ''
- slug: hp-ireland
  website: ''
- slug: ncr
  website: ''
- slug: sandvik
  website: ''
- slug: emc
  website: ''
- slug: netgear-international
  website: ''
- slug: synopsys
  website: ''
- slug: sap-business-objects
  website: ''
- slug: altera
  website: ''
- slug: microchip-technology
  website: ''
- slug: cartrawler
  website: ''
- slug: ibm
  website: ''
- slug: cadence
  website: ''
- slug: xilinx
  website: ''
- slug: bt
  website: ''
- slug: gartner
  website: ''
- slug: vce
  website: ''
- slug: skillsoft
  website: ''
- slug: yahoo-ireland
  website: ''
- slug: virgin-media
  website: ''
- slug: qlogic
  website: ''
- slug: red-hat
  website: ''
- slug: analog-devices
  website: ''
- slug: salesforce
  website: ''
- slug: teradata
  website: ''
- slug: nuance-communications
  website: ''
- slug: f-nua
  website: ''
- slug: mentor-graphics
  website: ''
- slug: ericsson
  website: ''
- slug: bentley-software
  website: ''
- slug: first-data
  website: ''
- slug: fleetmatics-group
  website: ''
- slug: microfocus
  website: ''
- slug: ptc-software
  website: ''
- slug: zynga
  website: ''
- slug: xerox
  website: ''
- slug: linkedin
  website: ''
- slug: twitter
  website: ''
- slug: orange-business-services
  website: ''
- slug: bmc
  website: ''
- slug: accenture
  website: ''
- slug: capita-managed-it-solutions
  website: ''
- slug: cms-distribution
  website: ''
- slug: iac-search-media
  website: ''
- slug: cms-peripherals
  website: ''
- slug: taxback-group
  website: ''
- slug: ptc-ireland
  website: ''
- slug: honeywell-process-solutions
  website: ''
- slug: trend-micro
  website: ''
- slug: extreme-networks
  website: ''
- slug: transas-marine
  website: ''
- slug: websense
  website: ''
- slug: commscope
  website: ''
- slug: workday
  website: ''
- slug: m-a-com-technology-solutions
  website: ''
- slug: stratus-technologies
  website: ''
- slug: humax
  website: ''
- slug: first-derivatives
  website: ''
- slug: abb-ltd
  website: ''
- slug: allstate-ni
  website: ''
- slug: arvato
  website: ''
- slug: fidelity-investments-ireland
  website: ''
- slug: molex
  website: ''
- slug: openet
  website: ''
- slug: cognex
  website: ''
- slug: monex
  website: ''
- slug: dialogic
  website: ''
- slug: westcoast
  website: ''
- slug: microwarehouse
  website: ''
- slug: schlumberger-information-solutions
  website: ''
- slug: premiere-conferencing
  website: ''
- slug: cross-refrigeration
  website: ''
- slug: afilias
  website: ''
- slug: siemens
  website: ''
- slug: citrix-systems-ireland
  website: ''
- slug: arvato-digital-services
  website: ''
- slug: cisco
  website: ''
- slug: version1
  website: ''
- slug: global-cloud-xchange
  website: ''
- slug: g4s-secure-solutions
  website: ''
- slug: fujitsu-ireland
  website: ''
- slug: j2-global
  website: ''
- slug: digital-river
  website: ''
- slug: ge-sensing
  website: ''
- slug: pramerica
  website: ''
- slug: dts
  website: ''
- slug: netiq-europe
  website: ''
- slug: logmein
  website: ''
- slug: pfh
  website: ''
- slug: dropbox-ireland
  website: ''
- slug: abtran
  website: ''
- slug: matrox
  website: ''
- slug: leaseplan-information-services
  website: ''
- slug: dk-donohoe
  website: ''
- slug: ewl-electric
  website: ''
- slug: avocent
  website: ''
- slug: amt-sybex
  website: ''
- slug: volex
  website: ''
- slug: fineos
  website: ''
- slug: conversant-media
  website: ''
- slug: datalex
  website: ''
- slug: verizon-ireland
  website: ''
- slug: 3m-ireland
  website: ''
- slug: quantcast-international
  website: ''
- slug: rigney-dolphin
  website: ''
- slug: itg-europe
  website: ''
- slug: imagine-communications
  website: ''
- slug: corvil
  website: ''
- slug: populis-ireland
  website: ''
- slug: creative-labs
  website: ''
- slug: intuition-publishing
  website: ''
- slug: zamano
  website: ''
- slug: convergys
  website: ''
- slug: aol-global-operations
  website: ''
- slug: asset-control
  website: ''
- slug: logicalis
  website: ''
- slug: electronic-arts
  website: ''
- slug: harkness-screens-international
  website: ''
- slug: guidewire-software
  website: ''
- slug: alcatel-lucent
  website: ''
- slug: bae-systems-detica
  website: ''
- slug: airspeed-communications
  website: ''
- slug: unity-technology-solutions
  website: ''
- slug: csg-international
  website: ''
- slug: option
  website: ''
- slug: moneymate
  website: ''
- slug: ion-trading
  website: ''
lever_companies:
- slug: microsoft
- slug: dell-ireland
- slug: apple-ireland
- slug: oracle
- slug: facebook
- slug: sandisk
- slug: kingston
- slug: vmware
- slug: intel-ireland
- slug: maxim-integrated-products
- slug: eircom
- slug: hp-ireland
- slug: ncr
- slug: sandvik
- slug: emc
- slug: netgear-international
- slug: synopsys
- slug: sap-business-objects
- slug: altera
- slug: microchip-technology
- slug: cartrawler
- slug: ibm
- slug: cadence
- slug: xilinx
- slug: bt
- slug: gartner
- slug: vce
- slug: skillsoft
- slug: yahoo-ireland
- slug: virgin-media
- slug: qlogic
- slug: red-hat
- slug: analog-devices
- slug: salesforce
- slug: teradata
- slug: nuance-communications
- slug: f-nua
- slug: mentor-graphics
- slug: ericsson
- slug: bentley-software
- slug: first-data
- slug: fleetmatics-group
- slug: microfocus
- slug: ptc-software
- slug: zynga
- slug: xerox
- slug: linkedin
- slug: twitter
- slug: orange-business-services
- slug: bmc
- slug: accenture
- slug: capita-managed-it-solutions
- slug: cms-distribution
- slug: iac-search-media
- slug: cms-peripherals
- slug: taxback-group
- slug: ptc-ireland
- slug: honeywell-process-solutions
- slug: trend-micro
- slug: extreme-networks
- slug: transas-marine
- slug: websense
- slug: commscope
- slug: workday
- slug: m-a-com-technology-solutions
- slug: stratus-technologies
- slug: humax
- slug: first-derivatives
- slug: abb-ltd
- slug: allstate-ni
- slug: arvato
- slug: fidelity-investments-ireland
- slug: molex
- slug: openet
- slug: cognex
- slug: monex
- slug: dialogic
- slug: westcoast
- slug: microwarehouse
- slug: schlumberger-information-solutions
- slug: premiere-conferencing
- slug: cross-refrigeration
- slug: afilias
- slug: siemens
- slug: citrix-systems-ireland
- slug: arvato-digital-services
- slug: cisco
- slug: version1
- slug: global-cloud-xchange
- slug: g4s-secure-solutions
- slug: fujitsu-ireland
- slug: j2-global
- slug: digital-river
- slug: ge-sensing
- slug: pramerica
- slug: dts
- slug: netiq-europe
- slug: logmein
- slug: pfh
- slug: dropbox-ireland
- slug: abtran
- slug: matrox
- slug: leaseplan-information-services
- slug: dk-donohoe
- slug: ewl-electric
- slug: avocent
- slug: amt-sybex
- slug: volex
- slug: fineos
- slug: conversant-media
- slug: datalex
- slug: verizon-ireland
- slug: 3m-ireland
- slug: quantcast-international
- slug: rigney-dolphin
- slug: itg-europe
- slug: imagine-communications
- slug: corvil
- slug: populis-ireland
- slug: creative-labs
- slug: intuition-publishing
- slug: zamano
- slug: convergys
- slug: aol-global-operations
- slug: asset-control
- slug: logicalis
- slug: electronic-arts
- slug: harkness-screens-international
- slug: guidewire-software
- slug: alcatel-lucent
- slug: bae-systems-detica
- slug: airspeed-communications
- slug: unity-technology-solutions
- slug: csg-international
- slug: option
- slug: moneymate
- slug: ion-trading
log_level: INFO
