name: Ireland Job Monitor

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build runtime config from template
        run: |
          cp config.yaml config.runtime.yaml
          sed -i "s/smtp.gmail.com/${{ secrets.SMTP_HOST }}/" config.runtime.yaml
          sed -i "s/587/${{ secrets.SMTP_PORT }}/" config.runtime.yaml
          sed -i "s/YOUR_SMTP_USERNAME/${{ secrets.SMTP_USER }}/" config.runtime.yaml
          sed -i "s/YOUR_SMTP_PASSWORD_OR_APP_PASSWORD/${{ secrets.SMTP_PASSWORD }}/" config.runtime.yaml
          sed -i "s/you@example.com/${{ secrets.MAIL_FROM }}/" config.runtime.yaml
          sed -i "s/\[\"you@example.com\"\]/[\"${{ secrets.MAIL_TO }}\"]/g" config.runtime.yaml
          sed -i "s/enabled: false/enabled: true/" config.runtime.yaml

      - name: Run monitor once
        run: python job_monitor.py --config config.runtime.yaml --once
